### PR TITLE
Skip undefined props when comparing nodes

### LINKED ISSUE #656: `equals` should skip null and undefined props
This is a continuation of #151, which fixed the skipping of *nodes*, but the same issue exists for *props*.

Here's an example to demonstrate the problem:

```jsx
import React from 'react';
import {shallow} from 'enzyme';

const Box = ({className}) => (
  <div className={className}/>
);

shallow(<Box/>).equals(<div/>); //=> false
shallow(<Box/>).equals(<div className={undefined}/>); //=> true
shallow(<Box className="awesome"/>).equals(<div className="awesome"/>); //=> true
```

`nodeEqual()` fails, because it expects `className={undefined}` property in the other component (`<div/>`). This is happening here https://github.com/airbnb/enzyme/blob/master/src/Utils.js#L94. Tested using the latest enzyme available on npm (`2.5.1`).

I think this case should be covered in enzyme by ignoring `null` and `undefined` props, which is what React does too. If everyone agrees, I can submit a PR to fix it ;)

### PR DESCRIPTION
**Pull request by vadimdemedes**
Fixes #656.

This PR ensures `null` and `undefined` props are skipped when comparing nodes:

```js
expect(nodeEqual(
   <div className={null} id={undefined} />,
   <div />
)).to.equal(true);
```

A helper function `cleanProps` removes all `null` and `undefined` props. I wanted to do that in `propsOfNode()`, but there are multiple `return` statements, which would result in a lot of repetition.

Let me know if this PR needs modification or anything else ;)

### CODE REVIEW

File: src/Utils.js [hunk 1]
```diff
@@ -83,13 +84,13 @@ export function nodeEqual(a, b, lenComp = is) {
...
-  const left = propsOfNode(a);
+  const left = cleanProps(propsOfNode(a));
   const leftKeys = Object.keys(left);
-  const right = propsOfNode(b);
+  const right = cleanProps(propsOfNode(b));
   for (let i = 0; i < leftKeys.length; i += 1) {
     const prop = leftKeys[i];
     // we will check children later
-    if (prop === 'children') {
+    if (prop === 'children' || !left[prop]) {
```
Comment (ljharb) [inline src/Utils.js]: shouldn't this be `left[prop] == null`, since `0` is falsy too?

File: src/Utils.js [hunk 2]
```diff
@@ -1,5 +1,6 @@
 /* eslint no-use-before-define:0 */
 import isEqual from 'lodash/isEqual';
+import isNil from 'lodash/isNil';
```
Comment (ljharb) [inline src/Utils.js]: i'm not sure why we need a dependency for `== null`?

File: src/Utils.js [hunk 3]
```diff
@@ -114,7 +115,7 @@ export function nodeEqual(a, b, lenComp = is) {
   }
 
   if (!isTextualNode(a)) {
-    const rightKeys = Object.keys(right);
+    const rightKeys = Object.keys(right).filter(key => !isNil(right[key]));
```
Comment (ljharb) [inline src/Utils.js]: let's just do `key => right[key] != null` - it's clearer and built-in.

Comment (vdemedes) [inline src/Utils.js]: Sure, agree.

File: src/Utils.js (hunk 2 above)
Comment (ljharb) [inline src/Utils.js]: a non-strict check against `null` is the sole exception :-)

**Comment by vdemedes** [comment]
Apparently, moving `cleanProps()` to `propsOfNode()` breaks this test: https://github.com/airbnb/enzyme/blob/master/test/ShallowTraversal-spec.jsx#L134. I guess `cleanProps()` should stay inside `nodeEqual()`. @ljharb What do you think?

**Comment by ljharb** [comment]
If we're going to ignore `null`, we need to ignore it consistently. In other words, searching for a value of `null` should be the same as a value of `undefined`, or as "absence".

In other words, if we're asking if a node has property "foo" equal to `null`, and it doesn't have the property "foo", then I'd expect it to pass.

File: src/Utils.js (hunk 1 above)
Comment (vdemedes) [inline src/Utils.js]: Ahh, leftover from debugging.

**Comment by vdemedes** [comment]
Ok, I see your point!

Regarding this test: https://github.com/airbnb/enzyme/blob/master/test/ShallowWrapper-spec.jsx#L577, let me clarify one last thing. If there are nodes with props equal to `null` or `undefined` and we're looking for them (like in the test), these nodes shouldn't be returned, because we treat those props as missing. 

```js
expect(wrapper.find({ prop: undefined })).to.have.length(0);
expect(wrapper.find({ prop: null })).to.have.length(0);
```

**Comment by ljharb** [comment]
yeah, that's a good point/wrinkle. It seems like the options are, when finding `{ foo: null, bar: 3 }`, to find anything that *omits* foo and *has* bar equal to 3 - or, to simply find anything that has bar equal to 3.

If we choose the former path, `.find({ prop: null })` will find everything. If we choose the latter, `.find({ prop: null })` will find nothing. I'm not sure if either makes sense.

**Comment by vdemedes** [comment]
I think there's a 3rd option. Check props in `find()` and throw if there are `null` or `undefined` values.

```js
find(props) {
  const hasNilProps = Object.keys(props).some(key => props[key] == null);

  if (hasNilProps) {
    throw new TypeError('Props can\'t have `null` or `undefined` values.');
  }

  // ...
}
```

What do you think?

**Comment by ljharb** [comment]
I think that's probably best, but then that means that it's a breaking change.

@lelandrichardson @Aweary @blainekasten @nfcampos what do you think?

**Comment by nfcampos** [comment]
this 3rd option is definitely the best of the three. this change should be accompanied with a note on the docs for `find()` saying that if you want to find nodes whose props are null you can use `findWhere`. maybe even the error message should mention this. what do you think?

**Comment by vdemedes** [comment]
I think @nfcampos's proposal is reasonable and makes this change clear to users.

**Comment by Aweary** [comment]
> I think @nfcampos's proposal is reasonable and makes this change clear to users.

Agreed 👍

**Comment by vdemedes** [comment]
Glad we agree, I'll update the PR!

**Comment by ljharb** [comment]
ok, so it looks like React ignores `undefined` but not `null` - http://stackoverflow.com/questions/34809178/react-js-default-prop-is-not-used-with-null-is-passed - so we should change this PR to continue to treat `null` as a valid, existing value.

**Comment by vdemedes** [comment]
@ljharb Good catch, will do!

**Comment by vdemedes** [comment]
PR updated, addressing all of the feedback above. Thanks to everyone!

One question: I put the warning about an error when using `.find()` and having some `undefined` props in the `docs/selector.md`. Should I put it in API docs for `.find()` or leave it there?

File: docs/api/ShallowWrapper/equals.md [hunk 4]
```diff
@@ -32,4 +32,4 @@ expect(wrapper.equals(<div className="foo bar" />)).to.equal(true);
 when you are calling it you are calling it with a ReactElement or a JSX expression.
 - Keep in mind that this method determines equality based on the equality of the node's children as
 well.
-
+- Following React's behavior, `.equals()` ignores properties, whose values are `undefined`.
```
Comment (nfcampos) [inline docs/api/ShallowWrapper/equals.md]: please remove the comma after 'properties'

**Comment by vdemedes** [comment]
All good now, thanks guys for the feedback ;)

File: src/ComplexSelector.js [hunk 5]
```diff
@@ -78,6 +78,13 @@ export default class ComplexSelector {
       return this.handleSelectors(selectors, wrapper);
     }
 
+    if (typeof selector === 'object' && selector !== null) {
+      const hasUndefinedValues = Object.keys(selector).some(key => selector[key] === undefined);
```
Comment (ljharb) [inline src/ComplexSelector.js]: `import values from 'object.values'` and you can do `values(selector).some(value => value === undefined)`

Comment (vdemedes) [inline src/ComplexSelector.js]: Good suggestion, updated!

File: src/Utils.js [hunk 6]
```diff
@@ -147,6 +147,18 @@ function isTextualNode(node) {
...
+function cleanProps(props) {
+  const newProps = {};
+
+  Object.keys(props)
+    .filter(key => props[key] !== undefined)
+    .forEach((key) => {
+      newProps[key] = props[key];
+    });
+
+  return newProps;
```
Comment (ljharb) [inline src/Utils.js]: alternatively:
```js
return entries(props)
  .filter(([, value]) => value !== undefined)
  .reduce((acc, [key, value]) => assign({}, acc, { [key]: value }), {});
```

**Comment by nfcampos** [comment]
@ljharb should we get this in for v3?

**Comment by ljharb** [comment]
I've rebased this on top of latest master; @aweary @nfcampos would you mind rereviewing?

File: packages/enzyme/src/selectors.js [hunk 7]
```diff
@@ -141,6 +142,10 @@ export function buildPredicate(selector) {
   // If the selector is an non-empty object, treat the keys/values as props
   if (typeof selector === 'object') {
     if (!Array.isArray(selector) && selector !== null && !isEmpty(selector)) {
+      const hasUndefinedValues = values(selector).some(value => value === undefined);
```
Comment (nfcampos) [inline packages/enzyme/src/selectors.js]: Why is this one a test of the value itself but the others are testing typeof?

File: packages/enzyme/src/Utils.js [hunk 8]
```diff
@@ -23,7 +23,9 @@ export function isCustomComponentElement(inst, adapter) {
 }
 
 function propsOfNode(node) {
-  return (node && node.props) || {};
+  return entries((node && node.props) || {})
+    .filter(([, value]) => typeof value !== 'undefined')
+    .reduce((acc, [key, value]) => ({ ...acc, [key]: value }), {});
```
Comment (nfcampos) [inline packages/enzyme/src/Utils.js]: This is rather ineffecient, creating as many objects as you have keys, I know this is a testing library, but if you have a lot of tests it starts to add up

File: packages/enzyme/src/RSTTraversal.js [hunk 9]
```diff
@@ -98,8 +99,17 @@ export function nodeHasId(node, id) {
...
+  return typeof v !== 'undefined' ? v : CAN_NEVER_MATCH;
+}
+function replaceUndefinedValues(obj) {
+  return entries(obj)
+    .reduce((acc, [k, v]) => ({ ...acc, [k]: replaceUndefined(v) }), {});
+}
+
 export function nodeMatchesObjectProps(node, props) {
-  return isSubset(propsOfNode(node), props);
+  return isSubset(propsOfNode(node), replaceUndefinedValues(props));
```
Comment (nfcampos) [inline packages/enzyme/src/RSTTraversal.js]: I don’t understand why we need this change. Don’t we throw if the received props contain undefined values?

File: packages/enzyme/src/selectors.js (hunk 7 above)
Comment (ljharb) [reply packages/enzyme/src/selectors.js]: My habit is to always use typeof for safety; babel makes this unnecessary. I'll make them all be the same.

File: packages/enzyme/src/Utils.js (hunk 8 above)
Comment (ljharb) [reply packages/enzyme/src/Utils.js]: Sure, I could mutate the accumulator since the overall reduce is pure.

File: packages/enzyme/src/RSTTraversal.js (hunk 9 above)
Comment (ljharb) [reply packages/enzyme/src/RSTTraversal.js]: In `find`, yes, but I don't think that's the only place this is called.

File: packages/enzyme/src/Utils.js (hunk 8 above)
Comment (ljharb) [reply packages/enzyme/src/Utils.js]: Done.

File: packages/enzyme/src/selectors.js (hunk 7 above)
Comment (ljharb) [reply packages/enzyme/src/selectors.js]: It's now consistent in the project.
