### PR TITLE
[Fix] Convert nodes to RST nodes before comparing

### LINKED ISSUE #1422: Add RST mapping to contains
I'm making an enzyme-inferno-adapter, but I've hit some problems getting the last few tests to pass. 

Enzyme requires `className` to be inside `props`. This is fine normally, because we can convert the inferno VNode tree to an enzyme RST tree. 

But when you call `contains`, enzyme compares the RST node to the newly created VNode. The RST node has `className` inside `props`, the inferno VNode has className on the vNode.

Example:

RST Node:

```js
{
type: 'div',
  props: {
    className: 'bar'
  }
}
```

Inferno VNode
```js
type: 'div',
  props: {
  },
  className: 'bar'
}
```

That means we can't call a method like this:
```js
const a = <div className="bar" />;
expect(mount(Component).contains(a)).to.equal(true);
```

Can we convert the node that `contains` is called with to an RST node before comparing? 

I'm happy to make the PR

### PR DESCRIPTION
**Pull request by eddyerburgh**
- Convert nodes in `contains` functions to RST before comparing 

- Fixes #1422

### CODE REVIEW

File: packages/enzyme/src/ReactWrapper.js [hunk 1]
```diff
@@ -446,7 +454,10 @@ class ReactWrapper {
    * @returns {Boolean}
    */
   containsAnyMatchingElements(nodes) {
-    return Array.isArray(nodes) && nodes.some(node => this.containsMatchingElement(node));
+    const rstNodes = nodes.map(getAdapter().elementToNode);
```
Comment (ljharb) [inline packages/enzyme/src/ReactWrapper.js]: this change makes `.map` be called before `Array.isArray` is called to ensure it's an array.

Let's change this to `if (!Array.isArray(nodes)) { return false; }` at the top of the function, and then we can do the entire check in a single `some`

File: packages/enzyme/src/ReactWrapper.js [hunk 2]
```diff
@@ -374,9 +375,13 @@ class ReactWrapper {
    * @returns {Boolean}
    */
   contains(nodeOrNodes) {
+    const isArray = Array.isArray(nodeOrNodes);
+    const rstNodeOrNodes = isArray
+      ? nodeOrNodes.map(getAdapter().elementToNode)
+      : getAdapter().elementToNode(nodeOrNodes);
     const predicate = Array.isArray(nodeOrNodes)
```
Comment (ljharb) [inline packages/enzyme/src/ReactWrapper.js]: this line can use `isArray` now, I think?

File: packages/enzyme/src/ReactWrapper.js [hunk 3]
```diff
@@ -374,9 +375,13 @@ class ReactWrapper {
...
-      ? other => containsChildrenSubArray(nodeEqual, other, nodeOrNodes)
-      : other => nodeEqual(nodeOrNodes, other);
+      ? other => containsChildrenSubArray(nodeEqual, other, rstNodeOrNodes)
```
Comment (ljharb) [inline packages/enzyme/src/ReactWrapper.js]: probably at this point, rather than two paired multiline ternaries, this would be better as an `if`/`else` branch.

File: packages/enzyme/src/ReactWrapper.js [hunk 4]
```diff
@@ -358,7 +358,8 @@ class ReactWrapper {
    * @returns {Boolean}
    */
   matchesElement(node) {
-    return this.single('matchesElement', () => nodeMatches(node, this.getNodeInternal(), (a, b) => a <= b));
+    const rstNode = getAdapter().elementToNode(node);
+    return this.single('matchesElement', () => nodeMatches(rstNode, this.getNodeInternal(), (a, b) => a <= b));
```
Comment (ljharb) [inline packages/enzyme/src/ReactWrapper.js]: let's do the elementToNode conversion here inside the arrow function, so that it happens after `this.single` succeeds.

**Comment by ljharb** [comment]
@eddyerburgh is this change not needed in `shallow` as well?

**Comment by eddyerburgh** [comment]
@ljharb Yes, you're right. I've only been implementing mount so haven't looked into shallow. I'll add the changes now

File: packages/enzyme/src/ReactWrapper.js [hunk 5]
```diff
@@ -374,9 +377,16 @@ class ReactWrapper {
...
   contains(nodeOrNodes) {
+    const adapter = getAdapter(this[OPTIONS]);
+
     const predicate = Array.isArray(nodeOrNodes)
-      ? other => containsChildrenSubArray(nodeEqual, other, nodeOrNodes)
-      : other => nodeEqual(nodeOrNodes, other);
+      ? other => containsChildrenSubArray(
+        nodeEqual,
+        other,
+        nodeOrNodes.map(adapter.elementToNode),
```
Comment (ljharb) [inline packages/enzyme/src/ReactWrapper.js]: Let’s make this use an arrow function, so adapters only get the single argument

**Comment by eddyerburgh** [comment]
It was already implemented for contains in ShallowWrapper, so I refactored `contains` in ReactWrapper. 

I also realized `containsAllMatchingElements` and `containsAnyMatchingElements` call `containsMatchingElement`, so I removed the unncessary calls to `containsMatchingElement`.

Finally, while I'm here, in `ReactWrapper.contains` there's no check that the node/nodes is a React element. Should I add a test and write a check, like there is [in `ShallowWrapper.contains`](https://github.com/airbnb/enzyme/blob/master/packages/enzyme/src/ShallowWrapper.js#L441)?

File: packages/enzyme/src/ReactWrapper.js (hunk 5 above)
Comment (ljharb) [reply packages/enzyme/src/ReactWrapper.js]: I also see this is how it already is in https://github.com/airbnb/enzyme/pull/1423/files#diff-fa27c82ee4fde075bae6173848e17c82R448; let’s change both

**Comment by ljharb** [comment]
> I also realized containsAllMatchingElements and containsAnyMatchingElements call containsMatchingElement, so I removed the unncessary calls to containsMatchingElement.

This was done intentionally, so there couldn’t be any drift between how these three methods worked - please keep them linked.

**Comment by ljharb** [comment]
In `mount`, someone might pass a DOM node; I’m not sure what the best solution is there.

**Comment by eddyerburgh** [comment]
>  so I removed the unncessary calls to `containsMatchingElement`

Sorry, I meant that I removed the unnecessary calls to `elementToNode`. They are all still linked.

**Comment by ljharb** [comment]
gotcha, sounds good then :-)

File: packages/enzyme/src/ReactWrapper.js (hunk 5 above)
Comment (eddyerburgh) [reply packages/enzyme/src/ReactWrapper.js]: > Let’s make this use an arrow function, so adapters only get the single argument
 
Do you mean the `nodeOrNodes` `map` callback should be an arrow function?

Comment (ljharb) [reply packages/enzyme/src/ReactWrapper.js]: yep! like `.map(x => adapter.elementToNode(x))`

Comment (eddyerburgh) [reply packages/enzyme/src/ReactWrapper.js]: Done 🙂

**Comment by eddyerburgh** [comment]
Thanks @ljharb . Is there anything else you need me to do to get this merged?

Also, do you know when this will be released?

**Comment by ljharb** [comment]
@eddyerburgh at the moment, you're good; i'm waiting for other collaborators to review it first.

After it's merged, it will be released whenever we're ready to publish the next one :-) hopefully soon.

**Comment by eddyerburgh** [comment]
@collaborators, could we get this reviewed and merged?

**Comment by ljharb** [comment]
The following packages are now released:
 - [enzyme v3.4.0](https://www.npmjs.com/package/enzyme)
 - [enzyme-adapter-react-16 v1.2.0](https://www.npmjs.com/package/enzyme-adapter-react-16)
 - [enzyme-adapter-react-16.3 v1.0.0](https://www.npmjs.com/package/enzyme-adapter-react-16.3)
 - [enzyme-adapter-react-16.2 v1.0.0](https://www.npmjs.com/package/enzyme-adapter-react-16.2)
 - [enzyme-adapter-react-16.1 v1.0.0](https://www.npmjs.com/package/enzyme-adapter-react-16.1)
 - [enzyme-adapter-react-15 v1.0.6](https://www.npmjs.com/package/enzyme-adapter-react-15)
 - [enzyme-adapter-react-15.4 v1.0.6](https://www.npmjs.com/package/enzyme-adapter-react-15.4)
 - [enzyme-adapter-react-14 v1.0.6](https://www.npmjs.com/package/enzyme-adapter-react-14)
 - [enzyme-adapter-react-13 v1.0.4](https://www.npmjs.com/package/enzyme-adapter-react-13)
 - [enzyme-adapter-utils v1.5.0](https://www.npmjs.com/package/enzyme-adapter-utils)
