### PR TITLE
Find html elements by class

### LINKED ISSUE #1929: Cannot find HTMLElements by class
### Current behavior

It appears that find, can't find html elements by class like HTMLAnchorElement

### Expected behavior

```
test("can find anchors", ()=> {
  const wrapper = mount(<div><a href="#"></a></div>);

  expect(wrapper.find('a').length).toBe(1); // passes
  expect(wrapper.childAt(0).instance()).toBeInstanceOf(HTMLAnchorElement); //passes
  expect(wrapper.find(HTMLAnchorElement).length).toBe(1); //fails
});

test("can find spans", ()=> {
  const wrapper = mount(<div><span>Test</span></div>);

  expect(wrapper.find('span').length).toBe(1); //passes
  expect(wrapper.childAt(0).instance()).toBeInstanceOf(HTMLSpanElement); //passes
  expect(wrapper.find(HTMLSpanElement).length).toBe(1); //fails
});

```

### Your environment

        "next": "^7.0.2",
        "react": "^16.4.2",
        "react-dom": "^16.4.2",
        "enzyme": "^3.5.0",
        "enzyme-adapter-react-16": "^1.3.0",
        "jest": "^23.5.0",

#### API

- [ ] shallow
- [X] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | ^3.5.0
| react               | ^16.4.2
| react-dom           |^16.4.2 
| react-test-renderer | ???
| adapter (below)     | ^1.3.0

#### Adapter

- [X] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

### PR DESCRIPTION
**Pull request by k3ithl1m**
Fixes #1929.

@ljharb This is the the test case that I wrote. Could you check and see if it's the right idea before I continue writing it for all the other elements?

### CODE REVIEW

File: packages/enzyme-test-suite/test/ReactWrapper-spec.jsx [hunk 1]
```diff
@@ -1526,6 +1528,123 @@ describeWithDOM('mount', () => {
         expect(wrapper.find(Component.displayName)).to.have.lengthOf(2);
       });
     });
+
+    
+    describe('find DOM elements by constructor', () => {
```
Comment (ljharb) [inline packages/enzyme-test-suite/test/ReactWrapper-spec.jsx]: i would do something like:
```suggestion
      describeWithDOM('find DOM elements by constructor', () => {
```
(import it from `'./_helpers'`) and it will skip the test for you when there's no DOM available.

File: packages/enzyme-test-suite/test/ReactWrapper-spec.jsx [hunk 2]
```diff
@@ -1526,6 +1528,123 @@ describeWithDOM('mount', () => {
...
+                <body>Hello</body>
+                <button type="button">Click Me!</button>
+              </div>
+            );
+          }
+        }
+        const mountedWrapper = mount(<Foo />);
+        const shallowWrapper = shallow(<Foo />);
+
+        expect(mountedWrapper.find(HTMLAnchorElement)).to.have.lengthOf(1);
```
[the remark this answers is not in the document]
Comment (k3ithl1m) [reply packages/enzyme-test-suite/test/ReactWrapper-spec.jsx]: Wao! That is really smart. Got it! Thanks

File: packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx [hunk 3]
```diff
@@ -1273,6 +1275,130 @@ describe('shallow', () => {
         expect(wrapper.find(Component.displayName)).to.have.lengthOf(2);
       });
     });
+
+    describeWithDOM('find DOM elements by constructor', () => {
+
+      it('finds DOM elements and attributes by constructor', () => {
+        /* eslint-env browser */
+        const map = {
```
Comment (ljharb) [inline packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx]: now that this map lives in two places, let's extract it out into a single file, and import it in both test files?

File: packages/enzyme-test-suite/test/ReactWrapper-spec.jsx [hunk 4]
```diff
@@ -1526,6 +1528,131 @@ describeWithDOM('mount', () => {
...
+          render() {
+            return (
+              <div id="container">
+                {Object.keys(map).map(Tag => <Tag key={Tag} />)}
+              </div>
+            );
+          }
+        }
+        const mountedWrapper = mount(<Foo />);
+        // const shallowWrapper = shallow(<Foo />);
```
Comment (ljharb) [inline packages/enzyme-test-suite/test/ReactWrapper-spec.jsx]:
```suggestion
```

File: packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx [hunk 5]
```diff
@@ -1273,6 +1275,130 @@ describe('shallow', () => {
...
+        class Foo extends React.Component {
+          render() {
+            return (
+              <div id="container">
+                {Object.keys(map).map(Tag => <Tag key={Tag} />)}
+              </div>
+            );
+          }
+        }
+        const shallowWrapper = shallow(<Foo />);
```
Comment (ljharb) [inline packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx]: Convention is just to call this `wrapper`.
```suggestion
        const wrapper = shallow(<Foo />);
```

File: packages/enzyme/src/selectors.js [hunk 6]
```diff
@@ -354,11 +354,20 @@ function matchDescendant(nodes, predicate) {
...
+ * https://stackoverflow.com/questions/384286/javascript-isdom-how-do-you-check-if-a-javascript-object-is-a-dom-object
+ *
+ * @param {EnzymeSelector} selector
  * @param {RSTNode} root
+ * //TODO Keith
  */
 export function reduceTreeBySelector(selector, root) {
-  if (typeof selector === 'function' || typeof selector === 'object') {
+  // Check if the selector is a HTMLElement and assign it to a variable
+  const isElement = (typeof HTMLElement === 'object') ? selector instanceof HTMLElement :
```
Comment (ljharb) [inline packages/enzyme/src/selectors.js]: I'd prefer to find a detection method that's not `instanceof`, since this doesn't work cross-realm, if possible.
```suggestion
  const isElement = typeof HTMLElement === 'object' ? selector instanceof HTMLElement : 
```

File: packages/enzyme/src/selectors.js [hunk 7]
```diff
@@ -354,11 +354,20 @@ function matchDescendant(nodes, predicate) {
...
+ *
+ * @param {EnzymeSelector} selector
  * @param {RSTNode} root
+ * //TODO Keith
  */
 export function reduceTreeBySelector(selector, root) {
-  if (typeof selector === 'function' || typeof selector === 'object') {
+  // Check if the selector is a HTMLElement and assign it to a variable
+  const isElement = (typeof HTMLElement === 'object') ? selector instanceof HTMLElement : 
+    typeof selector === 'object' && selector !== null && selector.nodeType === 1 && selector.nodeName === 'string';
```
Comment (ljharb) [inline packages/enzyme/src/selectors.js]: i'd also prefer a brand check over a duck-type check, if possible

File: packages/enzyme-test-suite/test/ReactWrapper-spec.jsx [hunk 8]
```diff
@@ -876,6 +877,7 @@ describeWithDOM('mount', () => {
     });
   });
 
+  // TODO Keith
```
Comment (ljharb) [inline packages/enzyme-test-suite/test/ReactWrapper-spec.jsx]: is this still a todo?

File: packages/enzyme-test-suite/test/ReactWrapper-spec.jsx [hunk 9]
```diff
@@ -1526,6 +1528,131 @@ describeWithDOM('mount', () => {
         expect(wrapper.find(Component.displayName)).to.have.lengthOf(2);
       });
     });
+
+    describeWithDOM('find DOM elements by constructor', () => {
+
```
Comment (ljharb) [inline packages/enzyme-test-suite/test/ReactWrapper-spec.jsx]:
```suggestion
```

File: packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx [hunk 10]
```diff
@@ -1273,6 +1275,130 @@ describe('shallow', () => {
         expect(wrapper.find(Component.displayName)).to.have.lengthOf(2);
       });
     });
+
+    describeWithDOM('find DOM elements by constructor', () => {
+
```
Comment (ljharb) [inline packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx]:
```suggestion
```

File: packages/enzyme-test-suite/test/ReactWrapper-spec.jsx (hunk 8 above)
Comment (k3ithl1m) [reply packages/enzyme-test-suite/test/ReactWrapper-spec.jsx]: This is to ease the process of me searching for the test cases if i need to modify it later on when I finish writing the feature

File: packages/enzyme/src/selectors.js (hunk 7 above)
Comment (k3ithl1m) [reply packages/enzyme/src/selectors.js]: Noted to both.

File: packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx [hunk 11]
```diff
@@ -1273,6 +1276,38 @@ describe('shallow', () => {
         expect(wrapper.find(Component.displayName)).to.have.lengthOf(2);
       });
     });
+
+    describeWithDOM('find DOM elements by constructor', () => {
+      it('finds DOM elements and attributes by constructor', () => {
+
```
Comment (ljharb) [inline packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx]:
```suggestion
```

File: packages/enzyme-test-suite/test/ReactWrapper-spec.jsx [hunk 12]
```diff
@@ -1526,6 +1529,38 @@ describeWithDOM('mount', () => {
         expect(wrapper.find(Component.displayName)).to.have.lengthOf(2);
       });
     });
+
+    describeWithDOM('find DOM elements by constructor', () => {
+      it('finds DOM elements and attributes by constructor', () => {
+
```
Comment (ljharb) [inline packages/enzyme-test-suite/test/ReactWrapper-spec.jsx]:
```suggestion
```

File: packages/enzyme-test-suite/test/Utils-spec.jsx [hunk 13]
```diff
@@ -693,6 +695,50 @@ describe('Utils', () => {
     });
   });
 
+  describe('isEmptyValue', () => {
```
Comment (ljharb) [inline packages/enzyme-test-suite/test/Utils-spec.jsx]: this shouldn't be appearing in the diff; it might need a rebase.

File: packages/enzyme-test-suite/test/_helpers/htmlMap.js [hunk 14]
```diff
@@ -0,0 +1,93 @@
...
+  bgsound: HTMLUnknownElement,
+  blink: HTMLUnknownElement,
+  multicol: HTMLUnknownElement,
+  nextid: HTMLUnknownElement,
+  rb: HTMLUnknownElement,
+  spacer: HTMLUnknownElement,
+  video: HTMLVideoElement,
+};
+
+export default map;
```
Comment (ljharb) [inline packages/enzyme-test-suite/test/_helpers/htmlMap.js]: this should probably be a function, so it can do runtime detection if needed.

File: packages/enzyme-test-suite/test/_helpers/htmlMap.js [hunk 15]
```diff
@@ -0,0 +1,100 @@
...
+  nextid: HTMLUnknownElement,
+  rb: HTMLUnknownElement,
+  spacer: HTMLUnknownElement,
+  video: HTMLVideoElement,
+};
+
+/**
+ * returns the map
+ */
+export function getMap() {
```
Comment (ljharb) [inline packages/enzyme-test-suite/test/_helpers/htmlMap.js]: this should be the default; and the object literal should be created inside the `getMap` function.

**Comment by ljharb** [comment]
I've rebased this; I think some things need to be rethought. The current map is needed for tests - of tag names to element constructors - but a similar map is needed in `selectors` to map from constructor to tag name.

Before making changed, please reset your local branch to match the rebased commit I've pushed up.

File: packages/enzyme/src/_helpers/getTagNameFromHTMLConstructor.js [hunk 16]
```diff
@@ -0,0 +1,97 @@
+
+/* eslint-env browser */
+/**
+ * map from constructor to tagName
+ */
+export default function getTagNameFromHTMLConstructor() {
+  return {
+    HTMLAnchorElement: a,
```
Comment (ljharb) [inline packages/enzyme/src/_helpers/getTagNameFromHTMLConstructor.js]: these have to be strings - ie:
```suggestion
    HTMLAnchorElement: 'a',
```
etc

File: packages/enzyme/src/selectors.js [hunk 17]
```diff
@@ -362,10 +363,22 @@ function matchDescendant(nodes, predicate) {
...
  * is handled by `buildPredicate`, or a complex CSS selector which
  * reduceTreeBySelector parses and reduces the tree based on the combinators.
- * @param {Function|Object|String} selector
+ *
+ * @param {EnzymeSelector} selector
  * @param {RSTNode} root
  */
 export function reduceTreeBySelector(selector, root) {
+  if (typeof selector !== 'string') {
+    const elements = elementsByConstructor(selector);
```
Comment (falsefalse) [inline packages/enzyme/src/selectors.js]: This pops "Update your Java installation" in IE11 😢 
https://github.com/ljharb/html-element-map/issues/3
