### PR TITLE
Fixed confusing prop selector behavior. Added helpful warning

### LINKED ISSUE #127: .find('[type=text]') behaves like .find('[type]')
If I have a component that renders a form that has one input with `type=text` on it and a few others that have `type` attributes with other values, `.find('[type=text'])` will give me all the nodes that have a `type` attribute. I would normally expect to get just the one that has a `type` attribute with a value of `"text"`, or see an error. To fix this in my test, I am quoting the value of the attribute: `.find('[type="text"]')`.

### PR DESCRIPTION
**Pull request by lelandrichardson**
to: @lencioni @ljharb @blainekasten 

When users were passing in selectors with a non-quoted string such as `[type=foo]` it was causing undesired behavior, matching any component that had the `type` prop.  This refactors the logic so that if the string is unquoted (and not an acceptable numeric literal or boolean), we throw a helpful error indicating that it should be quoted.

Fixes #127; Closes #129

### CODE REVIEW

File: src/Utils.js [hunk 1]
```diff
@@ -169,7 +170,14 @@ export function coercePropValue(propValue) {
   }
 
   // coerce to boolean
-  return propValue === 'true' ? true : false;
+  if (propValue === 'true') return true;
+  if (propValue === 'false') return false;
+
+  // user provided an unquoted string value
+  throw new Error(
```
Comment (ljharb) [inline src/Utils.js]: this should probably be a `TypeError`

File: src/Utils.js [hunk 2]
```diff
@@ -157,11 +158,11 @@ export function coercePropValue(propValue) {
 
   // if propValue includes quotes, it should be
   // treated as a string
-  if (propValue.search(/"/) !== -1) {
-    return propValue.replace(/"/g, '');
+  if (/^(['"]).*\1$/.test(propValue.trim())) {
```
Comment (ljharb) [inline src/Utils.js]: we should cache `propValue.trim()` so we don't have to call it twice.

Comment (lelandrichardson) [inline src/Utils.js]: I thought we don't care about performance? :grin:

File: src/Utils.js [hunk 3]
```diff
@@ -149,7 +149,8 @@ export function AND(fns) {
   };
 }
 
-export function coercePropValue(propValue) {
+export function coercePropValue(propValue, propName) {
```
Comment (blainekasten) [inline src/Utils.js]: every other internal function for this has had the signature of `fn(key, value) {}` maybe swapping these two for consistency sake?

Comment (lelandrichardson) [inline src/Utils.js]: :+1: sounds raisinable

File: src/Utils.js (hunk 1 above)
Comment (blainekasten) [inline src/Utils.js]: I also like what's going on this [PR](https://github.com/airbnb/enzyme/pull/110/files#diff-c33afeb87a3143ade6f458848655083bR141) with prefacing these errors with `Enzyme::Selector`

Comment (lelandrichardson) [inline src/Utils.js]: :+1: i know, i know. my laziness is getting the best of me.

File: src/Utils.js (hunk 2 above)
Comment (ljharb) [inline src/Utils.js]: producing a value once, and operating on that, rather than baking in the assumption that it will be idempotent when called twice, helps both clarity and performance :-p

Comment (lencioni) [inline src/Utils.js]: Alternatively to caching, we could do this by modifying the regex a little.

```js
const matches = propValue.match(/^\s*(['"])(.*)\1\s*$);
if (matches) {
  return matches[2];
}
```

or something like that

Comment (lencioni) [inline src/Utils.js]: Although I don't know if that's actually faster, so I would go with whatever is clearest (which is likely not the regex, lol).

**Comment by lencioni** [comment]
:+1:
