### PR TITLE
wrote the test case for props in async handler(new PR)

### LINKED ISSUE #1872: Child component props aren't updated after call to setState in async handler
I'm having trouble testing an event handler that does an async operation followed by a setState. Even when I wait for the setState to complete by awaiting a promise resolved from inside its callback, the component doesn't seem to fully re-render. What's weird is that I can confirm that the parent state is updated but props on a sub component that rely on that state are not. Even stranger, text that comes from those props inside the sub component is updated like normal.  I created a small script to reproduce the behavior. Note that after the onClick handler and setState finish this child component props are still `{ id: 'childDiv', counter: 1 }`. Only after a forced update do they change.

```jsx
import { mount } from 'enzyme';
import React, { Component } from 'react';
import Promise from 'bluebird';

class TestComponent extends Component {

  state = {
    counter: 1,
  };

  handleClick = async () => {
    await Promise.delay(100);
    return await new Promise((resolve) => {
      this.setState({ counter: 2 }, () => {
        resolve();
      });
    });
  };

  render() {
    return <div id={'parentDiv'} onClick={this.handleClick}>
      <TestSubComponent id={'childDiv'} counter={this.state.counter}/>
    </div>;
  }
}

class TestSubComponent extends Component {

  render() {
    return <div>{this.props.counter}</div>;
  }
}

describe('foo', () => {

  it('should foo', async () => {
    const component = mount(<TestComponent/>);

    // prints {"counter":1}
    console.log('=== parent state before click');
    console.log(JSON.stringify(component.state()));

    // prints { id: 'childDiv', counter: 1 }
    console.log('=== sub component props before click');
    console.log(component.find(TestSubComponent).props());

    // prints 1
    console.log('=== sub component props before click');
    console.log(component.find(TestSubComponent).text());

    await component.find('#parentDiv').props().onClick();

    // prints {"counter":2}
    console.log('=== parent state after click');
    console.log(JSON.stringify(component.state()));

    // prints { id: 'childDiv', counter: 1 }
    console.log('=== sub component props after click');
    console.log(component.find(TestSubComponent).props());

    // prints 2
    console.log('=== sub component text after click');
    console.log(component.find(TestSubComponent).text());

    component.update();

    // prints { id: 'childDiv', counter: 2 }
    console.log('=== sub component props after update');
    console.log(component.find(TestSubComponent).props());

  });

});
```

#### API

- [x] shallow
- [x] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.7.0
| react               | 16.3.1
| react-dom           | 16.3.1
| react-test-renderer | 16.3.2
| adapter (below)     |  enzyme-adapter-react-16.3@1.3.0

### PR DESCRIPTION
**Pull request by k3ithl1m**
Written the test case to test our props when there is an async handler #1872 @ljharb

Replaces #1930.

Closes #1872.

### CODE REVIEW

File: packages/enzyme-test-suite/test/ReactWrapper-spec.jsx [hunk 1]
```diff
@@ -3646,6 +3646,51 @@ describeWithDOM('mount', () => {
...
+    describe('props in async handler', () => {
+      class TestComponent extends React.Component {
+        constructor(props) {
+          super(props);
+          this.state = { counter: 1 };
+          this.handleClick = this.handleClick.bind(this);
+          this.delay = this.delay.bind(this);
+        }
+
+        async handleClick() {
```
Comment (ljharb) [inline packages/enzyme-test-suite/test/ReactWrapper-spec.jsx]: we can't actually use async functions in enzyme tests, but in this case it shouldn't matter since this function returns a promise.

File: packages/enzyme-test-suite/test/ReactWrapper-spec.jsx [hunk 2]
```diff
@@ -3646,6 +3646,51 @@ describeWithDOM('mount', () => {
...
+          this.delay(100);
```
Comment (ljharb) [inline packages/enzyme-test-suite/test/ReactWrapper-spec.jsx]: without `await this.delay(100)`, this line has no effect. Try this instead:
```suggestion
          return this.delay(100).then(() => {
            return new Promise(…)
          });
```

File: packages/enzyme-test-suite/test/ReactWrapper-spec.jsx [hunk 3]
```diff
@@ -3646,6 +3646,51 @@ describeWithDOM('mount', () => {
...
+          return new Promise((resolve) => {
+            this.setState({ counter: 2 }, () => {
+              resolve();
+            });
+          });
+        }
+
+        delay(ms) {
```
Comment (ljharb) [inline packages/enzyme-test-suite/test/ReactWrapper-spec.jsx]: this can just be a standalone function; it doesn't need to be an instance method.

File: packages/enzyme-test-suite/test/ReactWrapper-spec.jsx [hunk 4]
```diff
@@ -3646,6 +3646,51 @@ describeWithDOM('mount', () => {
...
+          return new Promise((resolve) => {
+            setTimeout(resolve, ms);
+          });
+        }
+
+        render() {
+          return (
+            <div id={'parentDiv'} onClick={this.handleClick}>
```
Comment (ljharb) [inline packages/enzyme-test-suite/test/ReactWrapper-spec.jsx]:
```suggestion
            <div id="parentDiv" onClick={this.handleClick}>
```

File: packages/enzyme-test-suite/test/ReactWrapper-spec.jsx [hunk 5]
```diff
@@ -3646,6 +3646,51 @@ describeWithDOM('mount', () => {
...
+              <TestSubComponent id={'childDiv'} counter={this.state.counter} />
```
Comment (ljharb) [inline packages/enzyme-test-suite/test/ReactWrapper-spec.jsx]:
```suggestion
              <TestSubComponent id="childDiv" counter={this.state.counter} />
```

File: packages/enzyme-test-suite/test/ReactWrapper-spec.jsx [hunk 6]
```diff
@@ -3646,6 +3652,45 @@ describeWithDOM('mount', () => {
...
+          );
+        }
+      }
+
+      class TestSubComponent extends React.Component {
+        render() {
+          return <div>{this.props.counter}</div>;
+        }
+      }
+      it('child component props should update after call to setState in async handler', async () => {
```
Comment (ljharb) [inline packages/enzyme-test-suite/test/ReactWrapper-spec.jsx]: this also needs to not be an async function

File: packages/enzyme-test-suite/test/ReactWrapper-spec.jsx [hunk 7]
```diff
@@ -3646,6 +3652,45 @@ describeWithDOM('mount', () => {
...
+
+      class TestSubComponent extends React.Component {
+        render() {
+          return <div>{this.props.counter}</div>;
+        }
+      }
+      it('child component props should update after call to setState in async handler', () => {
+        const component = mount(<TestComponent />);
+        component.find('#parentDiv').props().onClick();
+        expect(component.find(TestSubComponent).props()).to.eql({ id: 'childDiv', counter: 2 });
```
Comment (ljharb) [inline packages/enzyme-test-suite/test/ReactWrapper-spec.jsx]: so, i would expect this test to fail - because the `setState` has `delay(100)` on it.

It's impossible for the test to know when that async action is completed, unless it hardcodes a `delay(100)`, or unless the `onClick` returns a promise.

Comment (k3ithl1m) [reply packages/enzyme-test-suite/test/ReactWrapper-spec.jsx]: Yes. It will fail. I can work on trying to fix the bug too. Does the test look right though?

Comment (ljharb) [reply packages/enzyme-test-suite/test/ReactWrapper-spec.jsx]: No, to clarify - the test itself can't possibly pass. It's not possible for a test to magically wait for all async actions to be completed.

Comment (k3ithl1m) [reply packages/enzyme-test-suite/test/ReactWrapper-spec.jsx]: Ah okay. That makes sense. I was working on it last night and am trying to figure out.

I thought of setting a
‘Const promise = component.find(‘parentDiv’).props().onClick()’
And then promise.resolve with the expect in it. But it doesnt seem to work. I was thinking that it might be a reasonable approach because the handleClick returns a promise. 

Other than that, I assume that having a delay(100) is not the best way to approach this problem. 

What’s your thought?

Comment (ljharb) [reply packages/enzyme-test-suite/test/ReactWrapper-spec.jsx]: I'm starting to think there's not actually a bug here, and that the original issue is invalid.

Comment (ljharb) [reply packages/enzyme-test-suite/test/ReactWrapper-spec.jsx]: ok actually, the original issue in #1872 is still a bug - i think the test case needs a bit of tweaking to more closely match that (without using await or async functions)

Comment (k3ithl1m) [reply packages/enzyme-test-suite/test/ReactWrapper-spec.jsx]: I'm sorry but how should I go around writing this test? Or more, how am I able to know that I'm writing the test correctly?
