### PR TITLE
Fix to skip updates when nextState is null or undefined

### LINKED ISSUE #1783: Even when setState returns null, it calls cDU lifecycle.
**Describe the bug**
In React, if `setState` returns `null`, cDU is not called and so following does not make infinite loop even after cDU is called. (You can check it on [this codesandbox](https://codesandbox.io/s/18poplkr4q) by typing text on the input. It prints only one console log at a time.)

```js
export class TestComponent extends Component {
  constructor(props) {
    super(props);

    this.state = {};
  }

  componentDidUpdate() {
    this.setState(() => {
      return null;
    });
  }

  render() {
    return null;
  }
}
```

However, in `enzyme`, when I update component, i.e., invoking cDU with above component, will gives me infinite loop like

```
      at withSetStateAllowed (node_modules/enzyme/build/Utils.js:296:21)
      at ShallowWrapper.<anonymous> (node_modules/enzyme/build/ShallowWrapper.js:511:42)
      at ShallowWrapper.single (node_modules/enzyme/build/ShallowWrapper.js:1735:25)
      at ShallowWrapper.setState (node_modules/enzyme/build/ShallowWrapper.js:510:14)
      at TestComponent.ShallowWrapper.instance.setState (node_modules/enzyme/build/ShallowWrapper.js:190:35)
      at TestComponent.setState [as componentDidUpdate] (TestComponent.js:11:10)
      at node_modules/enzyme/build/ShallowWrapper.js:548:28
      at withSetStateAllowed (node_modules/enzyme/build/Utils.js:300:3)
      at ShallowWrapper.<anonymous> (node_modules/enzyme/build/ShallowWrapper.js:511:42)
      at ShallowWrapper.single (node_modules/enzyme/build/ShallowWrapper.js:1735:25)
      at ShallowWrapper.setState (node_modules/enzyme/build/ShallowWrapper.js:510:14)
      at TestComponent.ShallowWrapper.instance.setState (node_modules/enzyme/build/ShallowWrapper.js:190:35)
      at TestComponent.setState [as componentDidUpdate] (TestComponent.js:11:10)
      at node_modules/enzyme/build/ShallowWrapper.js:548:28
      // and repeat from line 1 to line 7
``` 

**To Reproduce**

1. `git clone https://github.com/Ailrun/enzyme-issue1783`
2. `npm i`
3. `npm test`

**Expected behavior**
Does not give infinite loop.

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Browser: is not used
 - Version: >=3.4.2, specifically, after https://github.com/airbnb/enzyme/pull/1742.

### PR DESCRIPTION
**Pull request by koba04**
Fix #1783 
This PR makes to prevent updates when setState returns `null` or `undefined`.
But the callback of setState's 2nd arguments should always be called as well as a behavior of ReactDOM.

### CODE REVIEW

File: packages/enzyme-test-suite/test/ReactWrapper-spec.jsx [hunk 1]
```diff
@@ -2460,6 +2460,64 @@ describeWithDOM('mount', () => {
...
+
+        render() {
+          return (
+            <div className={this.state.id} />
+          );
+        }
+      }
+
+      const wrapper = mount(<Foo />);
+      const spy = sinon.spy(wrapper.instance(), 'componentDidUpdate');
```
Comment (ljharb) [inline packages/enzyme-test-suite/test/ReactWrapper-spec.jsx]: i think we can check both null and undefined here by spying on componentDidUpdate?

File: packages/enzyme/src/ShallowWrapper.js [hunk 2]
```diff
@@ -446,6 +447,14 @@ class ShallowWrapper {
         const prevProps = instance.props;
         const prevState = instance.state;
         const prevContext = instance.context;
+
+        if (typeof state === 'function') {
+          state = state.call(instance, prevState, prevProps);
```
Comment (ljharb) [inline packages/enzyme/src/ShallowWrapper.js]: i'll tweak this to avoid reassignment

**Comment by koba04** [comment]
Travis is failed.
Ah, This behavior seems to be `>= 16`, so we need an adapter flag for this.

**Comment by ljharb** [comment]
@koba04 meaning, prior to react 16, it's an infinite loop?

**Comment by koba04** [comment]
@ljharb Yeah, prior to react 16, This seems to cause an infinite loop.

**Comment by ljharb** [comment]
actually i changed my mind; this should be in the adapter, so that react versions < 16 *always* get the infinite loop, even shallow-rendering when setState returns nullish.

**Comment by Ailrun** [comment]
I missed so many details in my issue... :disappointed: Thank you for noticing the version issue and fixing it too! You guys are really wonderfully awesome!
