### PR TITLE
Fix issue finding nested SFCs by constructor in mount

### LINKED ISSUE #262: wrapper.find() cannot retrieve stateless components
I'm trying to find rendered stateless components in a wrapper using `name`/`displayName` as selector (when using `mount`). For normal components `find` always returns selected components as expected, but for stateless components it returns nothing, even though they are there.

In [`findAllInRenderedTreeInternal`](https://github.com/airbnb/enzyme/blob/7efeda383c3c914f038ec0005ca493ed591b9d47/src/MountedTraversal.js#L236-L289) at [line 249](https://github.com/airbnb/enzyme/blob/7efeda383c3c914f038ec0005ca493ed591b9d47/src/MountedTraversal.js#L249) there is this a call

```
var publicInst = inst.getPublicInstance();
```

which calls `getPublicInstance` of `ReactCompositeComponent.js`:

```
  getPublicInstance: function () {
    var inst = this._instance;
    if (inst instanceof StatelessComponent) {
      return null;
    }
    return inst;
  },
```

Obviously, `find` will fail for stateless components since `getPublicInstance` always returns `null`. I'm wondering why in line 249 further up it is necessary to call `getPublicInstance` since there should be other ways to retrieve the element for testing.

I'm fairly new to `React` and `enzyme` so I am not sure if I am missing something.

### PR DESCRIPTION
**Pull request by iancmyers**
This fixes an issue where calling `.find` with an SFC constructor/function would fail to return instances of the the SFC in the tree.

This seems like a round-about way of getting at this. Is there a better way?

Fixes #262

### CODE REVIEW

File: src/Utils.js [hunk 1]
```diff
@@ -19,6 +19,10 @@ export function internalInstance(inst) {
     inst[internalInstanceKey(inst)];
 }
 
+export function isFunctionalComponent(inst) {
+  return inst.constructor.name === 'StatelessComponent';
```
Comment (ljharb) [inline src/Utils.js]: will `inst.constructor` always exist?

**Comment by iancmyers** [comment]
I've updated this with a different (correct-er) solution and another test.

File: src/Utils.js (hunk 1 above)
Comment (iancmyers) [inline src/Utils.js]: Provided what is passed to the function is an instance, yes, I think it will have a constructor.

File: src/MountedTraversal.js [hunk 2]
```diff
@@ -249,8 +255,7 @@ function findAllInRenderedTreeInternal(inst, test) {
     const internal = internalInstance(inst);
     return findAllInRenderedTreeInternal(internal, test);
   }
-
-  const publicInst = inst.getPublicInstance();
+  const publicInst = inst.getPublicInstance() || inst._instance;
```
Comment (ljharb) [inline src/MountedTraversal.js]: should the `_instance` stuff be moved into `getPublicInstance`?

Comment (iancmyers) [inline src/MountedTraversal.js]: I believe `.getPublicInstance` is a private method in React itself, which always returns `null` for SFCs, thus we fall back to `._instance`.

Comment (ljharb) [inline src/MountedTraversal.js]: ah ok, if it's a react method then we certainly can't fix that :-) LGTM

File: src/Utils.js (hunk 1 above)
Comment (lelandrichardson) [inline src/Utils.js]: let's maybe fence this with `inst && inst.constructor &&` anyway? I intend on using this in several places, and it seems possible for us to pass null in at some point...

Comment (iancmyers) [inline src/Utils.js]: @lelandrichardson @ljharb I've constructed a fence!

**Comment by lelandrichardson** [comment]
@iancmyers think you can rebase?
