### PR TITLE
[Fix] `{ShallowWrapper,ReactWrapper}#{type,props}()` should work with `null` nodes

### LINKED ISSUE #113: Cannot read property 'type' of null on ''.type()
If returning an empty string/null inside a react component and trying to call the type() function on that node will result in the following  error: Cannot read property 'type' of null. This can be reproduced when trying to the use the shallow rendering filterWhere() API method. 
Please see the below code snippet:

```javascript
const MyComp = ({foo}) => {
    return (
          <div>
                 <MyOtherComp />
                 {foo !== 0 && (
                      <MyAnotherComp />
                  )}
          </div>
    );
});

it('should rock the world', () => {
    const wrapper = shallow(<MyComp foo={0});
    const result = wrapper.findWhere(n => (
          n.type() ===  MyAnotherComp
    );
   expect('nothing because "Cannot read property \'type\' of null" will occur');
});
```
In my test I want to check if the value of a specific prop is for e.g. {bar} then component should not be rendered.
Are there any workarounds for this issue ?
Thanks !

### PR DESCRIPTION
**Pull request by ljharb**
Fixes #113.

^ @lelandrichardson, @goatslacker

### CODE REVIEW

File: src/ReactWrapper.js [hunk 1]
```diff
@@ -381,7 +381,10 @@ export default class ReactWrapper {
    * @returns {Object}
    */
   props() {
-    return this.single(n => getNode(n).props || {});
+    return this.single((n) => {
+      const node = getNode(n);
+      return node ? node.props || {} : {};
```
Comment (lelandrichardson) [inline src/ReactWrapper.js]: i think in the Utils file there is a `propsOfNode` function that we should probably be using instead of this. It deals with things like null being passed in.

File: src/ReactWrapper.js [hunk 2]
```diff
@@ -484,7 +487,10 @@ export default class ReactWrapper {
    * @returns {String|Function}
    */
   type() {
-    return this.single(n => getNode(n).type);
+    return this.single((n) => {
+      const node = getNode(n);
+      return node ? node.type : null;
```
Comment (lelandrichardson) [inline src/ReactWrapper.js]: :+1:

File: src/ReactWrapper.js (hunk 1 above)
Comment (ljharb) [inline src/ReactWrapper.js]: Sounds good - will that work the same in shallow and mount?

File: src/__tests__/ShallowWrapper-spec.js [hunk 3]
```diff
@@ -484,6 +484,53 @@ describe('shallow', () => {
       expect(spy.args[3][0].hasClass('bux')).to.equal(true);
     });
 
+    describeIf(!REACT013, 'stateless functional components', () => {
+      it('finds nodes', () => {
```
Comment (lelandrichardson) [inline src/__tests__/ShallowWrapper-spec.js]: these tests don't really seem to correspond with the behavior that was changed in this PR.... right?

Comment (ljharb) [inline src/__tests__/ShallowWrapper-spec.js]: the first "it" block is just a sanity check (and passed prior to my change) - the second one is the one that changed in this PR (and failed prior to my change)

same in the ReactWrapper specs

**Comment by jedwards1211** [comment]
@ljharb I'm wondering -- why would we want wrappers with null nodes to get passed to `findWhere` anyway?  I'm assuming there are still other methods that won't work with null nodes (I stumbled on this problem with `.text()`).  Wouldn't it be more robust to simply not pass wrappers with null nodes?

**Comment by ljharb** [comment]
That's a good point, and may be an alternative approach.

**Comment by jedwards1211** [comment]
Yeah I was going to post an issue about `.text()` in `.findWhere()` but I could just post an issue about null nodes instead

**Comment by ljharb** [comment]
Let's do that - findWhere and filterWhere etc perhaps shouldn't return `null` nodes? It's worth a discussion.

**Comment by jedwards1211** [comment]
Okay, sounds good

**Comment by jedwards1211** [comment]
And thanks for this awesome project!
