### PR TITLE
[Fix] `dive` should pass along options from `shallow`

### LINKED ISSUE #770: `shallow(<Component />, options1).dive(options2)` should merge and pass options through
https://github.com/airbnb/enzyme/blob/master/src/ShallowWrapper.js#L1033 - currently `.dive()` takes options and passes those along, but it doesn't inherit the original options passed to `shallow`.

It should.

### PR DESCRIPTION
**Pull request by blackpost38**
I made it, could you check this source?

I only added a logic that merges options to `dive()`

refs: #770

### CODE REVIEW

File: src/ShallowWrapper.js [hunk 1]
```diff
@@ -3,6 +3,7 @@ import flatten from 'lodash/flatten';
 import unique from 'lodash/uniq';
 import compact from 'lodash/compact';
 import cheerio from 'cheerio';
+import merge from 'lodash/merge';
```
Comment (ljharb) [inline src/ShallowWrapper.js]: we have `object.assign` available, please use that instead of adding a new dependency.

File: src/ShallowWrapper.js [hunk 2]
```diff
@@ -1023,14 +1024,15 @@ class ShallowWrapper {
...
+    const originalOptions = this.options;
     return this.single(name, (n) => {
       if (isDOMComponentElement(n)) {
         throw new TypeError(`ShallowWrapper::${name}() can not be called on DOM components`);
       }
       if (!isCustomComponentElement(n)) {
         throw new TypeError(`ShallowWrapper::${name}() can only be called on components`);
       }
-      return new ShallowWrapper(n, null, options);
+      return new ShallowWrapper(n, null, merge({}, originalOptions, options));
```
Comment (ljharb) [inline src/ShallowWrapper.js]: I think this can use `this.options` inline - the arrow function will ensure `this` is correct.

Comment (blackpost38) [inline src/ShallowWrapper.js]: you're right. okay, I'll fix it.

File: src/ShallowWrapper.js (hunk 1 above)
Comment (blackpost38) [inline src/ShallowWrapper.js]: I think we needs `merge` because `options` might be nested object.

```js
this.options = { context: {foo: 'hello'}};
options = {context: {bar: 'enzyme!'}};
assign({}, this.options, options)  // It will be {context: {bar: 'enzyme!'}}
```

Comment (nfcampos) [inline src/ShallowWrapper.js]: deep merging the options sounds like too much, i think eg merging the context as in your example should be done manually by the user. thoughts?

**Comment by nfcampos** [comment]
@ljharb this might be a major, no? it can break existing tests for components that depend on context being available/not available.

File: src/ShallowWrapper.js (hunk 1 above)
Comment (ljharb) [inline src/ShallowWrapper.js]: Yes, I think we want to avoid deep merging.

**Comment by ljharb** [comment]
@nfcampos my thinking is that a component that expects context would never be used or tested without context - thus, what would be the use case for having a test that this change breaks?

This also will pass through the lifecycle flag, but we're planning to enable that by default in the next major anyways.

File: src/ShallowWrapper.js (hunk 1 above)
Comment (blackpost38) [inline src/ShallowWrapper.js]: oh, okay. i got it. I'll fix this and then send PR 😄 

thanks for your feedbacks 👍

**Comment by blackpost38** [comment]
I fixed it. I tried to apply your feedbacks.

Could you check it out? thanks!

**Comment by nfcampos** [comment]
@ljharb only got to this now — ive been without internet at home for the better part of two weeks :( — thinking about this some more I could agree with this being a patch, arguably the previous behaviour was wrong, the expectation in react for a child to receive the same thing in context as its parent, what do you think?

**Comment by ljharb** [comment]
I think I agree that it should be a patch.

**Comment by nfcampos** [comment]
@blackpost38 do you mind reabsing this on latest master?

**Comment by blackpost38** [comment]
@nfcampos It's done.

**Comment by nfcampos** [comment]
Thanks @blackpost38 !
