### PR TITLE
[fix] `shallow`: A nested ForwardRef is not recognized as a valid component by `dive()`

### LINKED ISSUE #1830: A nested ForwardRef is not recognized as a valid component by shallow dive()
**Describe the bug**
A nested ForwardRef is not recognized as a valid component when I do shallow dive() to it.

**To Reproduce**
1. Sample code:
```javascript
  import * as React from "react";
  import { shallow } from 'enzyme';

  const Component = () => <div/>
  const HOCOne = (WrappedComponent) => React.forwardRef(() => <WrappedComponent/>)
  const HOCTwo = (WrappedComponent) => React.forwardRef(() => <WrappedComponent/>)
  const WithNestedForwarRefComponent = HOCTwo(HOCOne(Component)))
  
  const vDomWrapper = shallow(<WithNestedForwarRefComponent/>);
  
```
2. Then debug() and dive() vDomWrapper:
```javascript
  vDomWrapper.debug()
  vDomWrapper.dive()
```
3. Debug output:
`<ForwardRef(HOCOne(Component)) />`
4. See dive() error:
`TypeError: ShallowWrapper::dive() can only be called on components`

**Expected behavior**
A ForwardRef component must be recognized as such and it must be possible to do dive () on it.

**Desktop:**
 - OS: Ubuntu 18.04
 - Node: 8.11.3
 - Enzyme: 3.6.0
 - React: 16.5.0

### PR DESCRIPTION
**Pull request by SinHouse**
Fixes #1830

Other: 
- Added Utils.isCustomComponentElement tests
- Pass test:all
- Pass lint

### CODE REVIEW

File: packages/enzyme/src/Utils.js [hunk 1]
```diff
@@ -42,7 +42,7 @@ export function makeOptions(options) {
 }
 
 export function isCustomComponentElement(inst, adapter) {
-  return !!inst && adapter.isValidElement(inst) && typeof inst.type === 'function';
```
Comment (ljharb) [inline packages/enzyme/src/Utils.js]: Please add tests that ensure `isCustomComponentElement` returns `false` for HTML elements.

Comment (SinHouse) [reply packages/enzyme/src/Utils.js]: Hi @ljharb,

I thing the changes are ready but fails the Travis job that build react 16.5 with node 8.

My develop machine use node 8.11.3 with Ubuntu 18.04 and I pass test:all and the lint tests.

Is it possible that it' s a specific problem with the Travis environment or is the problem in my code?

Thanks,

Comment (ljharb) [reply packages/enzyme/src/Utils.js]: Since it errored, instead of failed, it's an issue with travis.

File: packages/enzyme-adapter-react-16.3/src/ReactSixteenThreeAdapter.js [hunk 2]
```diff
@@ -483,6 +484,10 @@ class ReactSixteenThreeAdapter extends EnzymeAdapter {
     return typeOfNode(fragment) === Fragment;
   }
 
+  isForwardRef(forwardRef) {
```
[the remark this answers is not in the document]
Comment (SinHouse) [reply packages/enzyme-adapter-react-16.3/src/ReactSixteenThreeAdapter.js]: I agree that isCustomComponentElement can be an adapter competence because its implementation changes between React versions.

The problem is that I have to identify a forwardRef in a robust way and therefore I need to access the isForwardRef dependency of the react-is package available in the current dependencies of the adapter.

A forwardRef component is an object and not a function like other custom components, this is why isCustomComponentElement fails with them.

The current solution just add changes to 16 and 16.3 adapters, it's a similar solution of the current isFragment adapter method present only in the React 16 adapters.

The proposed solution to expand the current interface adapter to include the isCustomComponentElement method add changes to all the adapters but I agree can be a better solution.

Right now I can' t think of a cleaner or more robust solution than the previous ones, I'm sorry.

I wait for you to know your opinion about it.

**Comment by SinHouse** [comment]
Hi @ljharb,

Utils.isCustomComponentElement seems used only by ShallowWrapper.dive()

Is it a good idea remove isCustomComponentElement from Utils and call adapter.isCustomComponentElement directly?

**Comment by SinHouse** [comment]
Hi @ljharb,

Please, can you update the pull request state? Thanks a lot,

File: packages/enzyme-adapter-react-13/src/ReactThirteenAdapter.js [hunk 3]
```diff
@@ -271,6 +271,10 @@ class ReactThirteenAdapter extends EnzymeAdapter {
     return typeof object === 'string' || typeof object === 'function';
   }
 
+  isCustomComponentElement(inst) {
+    return !!inst && this.isValidElement(inst) && typeof inst.type === 'function';
```
Comment (ljharb) [inline packages/enzyme-adapter-react-13/src/ReactThirteenAdapter.js]: for now, let's have every adapter where it matches, directly use the implementation from utils

File: packages/enzyme-adapter-react-16.3/src/ReactSixteenThreeAdapter.js [hunk 4]
```diff
@@ -483,6 +484,11 @@ class ReactSixteenThreeAdapter extends EnzymeAdapter {
     return typeOfNode(fragment) === Fragment;
   }
 
+  isCustomComponentElement(inst) {
+    const isFunctionOrForwardRef = () => typeof inst.type === 'function' || isForwardRef(inst);
```
Comment (ljharb) [inline packages/enzyme-adapter-react-16.3/src/ReactSixteenThreeAdapter.js]: i think these can be inlined; no need to create a function for it

File: packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js [hunk 5]
```diff
@@ -485,6 +486,11 @@ class ReactSixteenAdapter extends EnzymeAdapter {
     return typeOfNode(fragment) === Fragment;
   }
 
+  isCustomComponentElement(inst) {
+    const isFunctionOrForwardRef = () => typeof inst.type === 'function' || isForwardRef(inst);
```
Comment (ljharb) [inline packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js]: same here

File: packages/enzyme/src/Utils.js [hunk 6]
```diff
@@ -42,7 +42,7 @@ export function makeOptions(options) {
...
+  return adapter.isCustomComponentElement(inst);
```
Comment (ljharb) [inline packages/enzyme/src/Utils.js]: this needs a fallback for the case where an adapter lacks `isCustomComponentElement`.

File: packages/enzyme-adapter-react-16.3/src/ReactSixteenThreeAdapter.js (hunk 4 above)
Comment (SinHouse) [reply packages/enzyme-adapter-react-16.3/src/ReactSixteenThreeAdapter.js]: done, the result is a little more confusing but it's faster :+1:

File: packages/enzyme/src/Utils.js (hunk 6 above)
Comment (SinHouse) [reply packages/enzyme/src/Utils.js]: done,

**Comment by SinHouse** [comment]
Thanks to you @ljharb
