### PR TITLE
Fixed issue with undefined being wrapped as nodes while constructing …

### LINKED ISSUE #554: ref('...').isEmpty() is always false
Example of `ref()` usage with unexpected behavior:

```js
const wrapper = mount(<Component />);
const x = wrapper.ref('definitely-not-a-ref');
x.node // => undefined
x.nodes // => actual [undefined], expected []
x.length // => actual 1, expected 0
x.isEmpty() // => actual false, expected true
```

Contrast with behavior of `find`

```js
const wrapper = mount(<Component />);
const x = wrapper.find('.definitely-not-a-class');
x.node // => undefined
x.nodes // => []
x.length // => 0
x.isEmpty() // => true
```

### PR DESCRIPTION
**Pull request by Andarist**
…ReactWrapper (fixes #554)

### CODE REVIEW

File: test/ReactWrapper-spec.jsx [hunk 1]
```diff
@@ -3005,5 +3005,18 @@ describeWithDOM('mount', () => {
...
+        class WithoutRef extends React.Component {
+          render() { return <div />; }
+        }
+        const wrapper = mount(<WithoutRef />);
+        const ref = wrapper.ref('not-a-ref');
+
+        expect(ref.length).to.equal(0);
+        expect(ref.isEmpty()).to.equal(true);
+      });
+    });
```
Comment (Aweary) [inline test/ReactWrapper-spec.jsx]: Can you name the top level `describe` block `.ref()` so we can put future tests for `ref` in there too? Thanks!

**Comment by Andarist** [comment]
@Aweary corrected with your suggestion

**Comment by Aweary** [comment]
LGTM, thanks
